## 多语言BERT模型——M-BERT

In [1]:
! pip install transformers==3.5.1

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 172.0/172.0 kB 3.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 500.5/500.5 kB 21.9 MB/s eta 0:00:00
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [2]:
from transformers import BertTokenizer, BertModel

下载预训练的M-BERT模型以及它的词元分析器

In [3]:
model = BertModel.from_pretrained('bert-base-multilingual-cased')
tokenizer = BertTokenizer.from_pretrained('bert-base-multilingual-cased')

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/625 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/714M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/996k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


设定输入句子。这里使用一个法语句子作为输入。

In [4]:
sentence = "C'est une si belle journée"
inputs = tokenizer(sentence, return_tensors="pt")
print(inputs)

{'input_ids': tensor([[  101,   140,   112, 10176, 10231, 10294, 40094, 46940,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1]])}


In [5]:
outputs = model(**inputs)
print(outputs)

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[ 0.3442,  0.2929, -0.1433,  ...,  0.2416, -0.2179,  0.2409],
         [ 0.3670,  0.1821,  0.2877,  ...,  0.0496, -0.3007, -0.1949],
         [ 0.0200,  0.1593,  0.5889,  ...,  0.1803, -0.8438,  0.1394],
         ...,
         [ 0.8716,  0.0774, -0.7843,  ...,  0.0664, -0.7128,  0.7696],
         [ 0.7305,  0.1043, -0.1287,  ...,  0.1224, -0.2657,  0.2772],
         [ 0.6561,  0.3084,  0.5651,  ...,  0.3598, -0.2188,  0.2228]]],
       grad_fn=<NativeLayerNormBackward0>), pooler_output=tensor([[ 0.4168, -0.0315,  0.3825, -0.2052, -0.3781,  0.6294,  0.2403,  0.2353,
         -0.5443,  0.4851, -0.0137, -0.2174, -0.2432, -0.2148,  0.2238, -0.2945,
          0.8033,  0.1290,  0.1153, -0.4026, -1.0000, -0.0850, -0.4064, -0.1970,
         -0.4523,  0.1074, -0.1899,  0.1125,  0.2262, -0.1150, -0.0028, -1.0000,
          0.6569,  0.8341,  0.2325, -0.1703,  0.1096,  0.3254,  0.2662, -0.4426,
         -0.2640,  0.0809, -0.15

In [6]:
hidden_rep = outputs.last_hidden_state
cls_rep = outputs.pooler_output
print(hidden_rep)
print(cls_rep)

tensor([[[ 0.3442,  0.2929, -0.1433,  ...,  0.2416, -0.2179,  0.2409],
         [ 0.3670,  0.1821,  0.2877,  ...,  0.0496, -0.3007, -0.1949],
         [ 0.0200,  0.1593,  0.5889,  ...,  0.1803, -0.8438,  0.1394],
         ...,
         [ 0.8716,  0.0774, -0.7843,  ...,  0.0664, -0.7128,  0.7696],
         [ 0.7305,  0.1043, -0.1287,  ...,  0.1224, -0.2657,  0.2772],
         [ 0.6561,  0.3084,  0.5651,  ...,  0.3598, -0.2188,  0.2228]]],
       grad_fn=<NativeLayerNormBackward0>)
tensor([[ 0.4168, -0.0315,  0.3825, -0.2052, -0.3781,  0.6294,  0.2403,  0.2353,
         -0.5443,  0.4851, -0.0137, -0.2174, -0.2432, -0.2148,  0.2238, -0.2945,
          0.8033,  0.1290,  0.1153, -0.4026, -1.0000, -0.0850, -0.4064, -0.1970,
         -0.4523,  0.1074, -0.1899,  0.1125,  0.2262, -0.1150, -0.0028, -1.0000,
          0.6569,  0.8341,  0.2325, -0.1703,  0.1096,  0.3254,  0.2662, -0.4426,
         -0.2640,  0.0809, -0.1504,  0.2908, -0.2625, -0.4123, -0.1935,  0.1543,
         -0.3677,  0.2359,  0

然后，我们可以用中文进行输入尝试

In [7]:
sentence = "你好，我的朋友，我的名字叫李华。"
inputs = tokenizer(sentence, return_tensors="pt")
print(inputs)

{'input_ids': tensor([[  101,  2262,  3240, 10064,  3976,  5718,  4462,  2731, 10064,  3976,
          5718,  2774,  3354,  2752,  4489,  2674,  1882,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}


In [8]:
outputs = model(**inputs)
print(outputs)

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[ 0.2242,  0.3158,  0.0664,  ...,  0.5067,  0.0228,  0.0605],
         [ 0.3021,  0.1171,  0.1906,  ...,  1.3279,  0.6891,  0.5034],
         [-0.0406, -0.0654,  0.4992,  ...,  0.7504,  0.3624,  0.1927],
         ...,
         [ 0.5157,  1.1622,  0.6268,  ..., -0.0172, -0.1573, -0.1970],
         [ 0.0079,  0.3284,  0.7852,  ...,  0.5092, -0.0847,  0.4146],
         [ 0.3712,  0.3977,  0.6864,  ...,  1.0786,  0.1312,  0.3079]]],
       grad_fn=<NativeLayerNormBackward0>), pooler_output=tensor([[ 0.4629, -0.0930,  0.1500, -0.3031, -0.0335,  0.3205,  0.3334,  0.1706,
         -0.3757,  0.2571,  0.0743, -0.1436, -0.1652, -0.0996,  0.1830, -0.3642,
          0.6779,  0.0089,  0.1577, -0.2975, -1.0000, -0.1077, -0.2387, -0.2136,
         -0.5047,  0.0162, -0.1763,  0.1353,  0.1574, -0.0229,  0.1814, -1.0000,
          0.6023,  0.6708,  0.1952, -0.0866,  0.1791,  0.3237,  0.2627, -0.4314,
         -0.2299, -0.0450, -0.20

In [9]:
hidden_rep = outputs.last_hidden_state
cls_rep = outputs.pooler_output

In [11]:
print(hidden_rep)
print(hidden_rep.shape)

tensor([[[ 0.2242,  0.3158,  0.0664,  ...,  0.5067,  0.0228,  0.0605],
         [ 0.3021,  0.1171,  0.1906,  ...,  1.3279,  0.6891,  0.5034],
         [-0.0406, -0.0654,  0.4992,  ...,  0.7504,  0.3624,  0.1927],
         ...,
         [ 0.5157,  1.1622,  0.6268,  ..., -0.0172, -0.1573, -0.1970],
         [ 0.0079,  0.3284,  0.7852,  ...,  0.5092, -0.0847,  0.4146],
         [ 0.3712,  0.3977,  0.6864,  ...,  1.0786,  0.1312,  0.3079]]],
       grad_fn=<NativeLayerNormBackward0>)
torch.Size([1, 18, 768])


In [12]:
print(cls_rep)
print(cls_rep.shape)

tensor([[ 0.4629, -0.0930,  0.1500, -0.3031, -0.0335,  0.3205,  0.3334,  0.1706,
         -0.3757,  0.2571,  0.0743, -0.1436, -0.1652, -0.0996,  0.1830, -0.3642,
          0.6779,  0.0089,  0.1577, -0.2975, -1.0000, -0.1077, -0.2387, -0.2136,
         -0.5047,  0.0162, -0.1763,  0.1353,  0.1574, -0.0229,  0.1814, -1.0000,
          0.6023,  0.6708,  0.1952, -0.0866,  0.1791,  0.3237,  0.2627, -0.4314,
         -0.2299, -0.0450, -0.2033,  0.1864, -0.1793, -0.3131, -0.1666,  0.3684,
         -0.4719,  0.2259,  0.0107,  0.3008,  0.4740,  0.3360,  0.2352,  0.3131,
          0.2984,  0.2732,  0.2354, -0.1566,  0.1132,  0.1490,  0.1614, -0.1800,
         -0.1522, -0.3488,  0.0176, -0.2408,  0.5931, -0.3341, -0.1860, -0.5058,
         -0.2543,  0.1410, -0.0057, -0.2683,  0.4331,  0.3365,  0.0204, -0.1640,
         -0.3379, -0.4264, -0.4214,  0.1231, -0.1765,  0.1797,  0.2940, -0.3207,
          0.1896, -0.0671,  0.2142,  0.5353, -0.2379,  0.4426, -0.0242, -0.0573,
         -0.8443, -0.1662, -

`hidden_rep`包含句子中所有标记的特征，而`cls_head`包含`[CLS]`标记的特征，它持有这句话的总特征。以这种方式，可以用与其他BERT模型相同的方式来使用预训练的M-BERT模型。

### M-BERT单一的模型是可以实现跨语言的知识迁移
例如，你可以使用英文数据集进行训练，然后使用中文数据集进行测试，但是这样的微调仍然可以取得较好的效果。

`XNLI`数据集就是这样做的，它使用英语数据集进行训练，然后使用多种语言的数据集进行测试。

**跨语言知识迁移的原因主要如下**
- M-BERT模型的通用性并不取决于词汇的重叠度
- M-BERT模型的通用性取决于类型相似度（主谓宾的语法结构）
- M-BERT模型可以处理语码混用文本，但不能处理音译文本